"""new fields in user model

Revision ID: 42066db72752
Revises: 08ebd0203ccf
Create Date: 2023-01-02 18:19:42.852220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42066db72752'
down_revision = '08ebd0203ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
